### PR TITLE
Updates for Django 1.8 and Python 3.4 support with complex testing

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Django denorm tests pass in all desired environments. It is tested in combinations of Django 1.5 to Django 1.8 and Python 2.6, 2.7, 3.4 versions with all supported databases.

Django 1.9 and master is tested with negative result, but it is ignored. The fixing is waiting for somebody more determined.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
Couldn't be the Travis tests enabled for main django-denorm branch? Or is there any problem with it?

**Comment by initcrash** [comment]
I wanted to, but since i moved the project from my personal account to the organization i have not been able to figure out how to enable Travis for it. Any pointers?

**Comment by PetrDlouhy** [comment]
If you are admin of django-denorm organization, I suspect, you can do it at: https://travis-ci.org/profile/django-denorm (right top corner profile -> accounts -> django-leaflet)

**Comment by bashu** [comment]
@PetrDlouhy fixed

**Comment by PetrDlouhy** [comment]
Very nice :-)

**Pull request merged**
