### PR TITLE
Django 1.7

### LINKED ISSUE #36: Incompatibility with Django 1.7 and migrations
Now that django has migrations, it would be nice if django-denorm could play nicely.
At present, running manage.py migrate causes this error:

ImportError: Module "denorm.fields.DenormDBField" does not define a "DenormDBField" attribute/class

However, commenting out the decorator and property function while the migration runs solves the problem, so it seems it can't be that complex to fix. As a temporary workaround, wrapping the decorator and function in:

    if sys.argv[1] not in 'migrate makemigrations'.split():
        @denormalised
        def ...

solves the problem too.

### PR DESCRIPTION
**Pull request by ErwinJunge**
This adds a deconstruct method, to add compatibility with django 1.7 migrations
Fixes #36

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
What is the problem with this PR?

**Comment by Uznick** [comment]
Any progress with this task? It's already Django 1.8 :(

**Comment by PetrDlouhy** [comment]
I have made django-denorm compatible with all Django versions from 1.5 to 1.8 including all the testing: https://github.com/whyflyru/django-denorm/pull/3

**Comment by bashu** [comment]
closed via @e1e1a7d8523d80ea2eae61ad05ac56ccfd7716ad

**Pull request closed without merging**
